version: '3'
services:
  web-react:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
  test-react:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: ["npm","run","test"]